In [55]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/cars.csv')

In [56]:
df.head(15)

      brand  km_driven    fuel         owner  selling_price
0    Maruti     145500  Diesel   First Owner         450000
1     Skoda     120000  Diesel  Second Owner         370000
2     Honda     140000  Petrol   Third Owner         158000
3   Hyundai     127000  Diesel   First Owner         225000
4    Maruti     120000  Petrol   First Owner         130000
5   Hyundai      45000  Petrol   First Owner         440000
6    Maruti     175000     LPG   First Owner          96000
7    Maruti       5000  Petrol  Second Owner          45000
8    Toyota      90000  Diesel   First Owner         350000
9      Ford     169000  Diesel   First Owner         200000
10  Renault      68000  Diesel  Second Owner         500000
11   Maruti     100000  Petrol  Second Owner          92000
12   Maruti     140000  Diesel  Second Owner         280000
13   Maruti      80000  Petrol  Second Owner         200000
14   Maruti      90000  Petrol  Second Owner         180000

In [57]:
df['fuel'].value_counts()

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

In [58]:
df['fuel'].nunique()

4

In [59]:
df.shape

(8128, 5)

## OneHot Encoding using Pandas

In [60]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

## k-1 One-hot-encoding

In [61]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

One-hot-encoding using sklearn

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [63]:
X_train.head()

        brand  km_driven    fuel         owner
821   Hyundai      38000  Petrol   First Owner
706    Maruti     180000  Petrol  Second Owner
152      Tata      11000  Petrol   First Owner
1872      BMW       8500  Diesel   First Owner
7949   Toyota     170000  Diesel   First Owner

In [64]:
from sklearn.preprocessing import OneHotEncoder

In [65]:
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [68]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [70]:
X_test_new = ohe.transform(X_train[['fuel','owner']])

In [71]:
X_train[['brand','km_driven']].values

array([['Hyundai', 38000],
       ['Maruti', 180000],
       ['Tata', 11000],
       ...,
       ['Chevrolet', 50000],
       ['Hyundai', 70000],
       ['Honda', 100000]], dtype=object)

In [72]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 38000, 0, ..., 0, 0, 0],
       ['Maruti', 180000, 0, ..., 1, 0, 0],
       ['Tata', 11000, 0, ..., 0, 0, 0],
       ...,
       ['Chevrolet', 50000, 1, ..., 1, 0, 0],
       ['Hyundai', 70000, 1, ..., 0, 0, 0],
       ['Honda', 100000, 0, ..., 1, 0, 0]], dtype=object)

## 4.OneHotEncoding with Top Category

In [73]:
counts = df['brand'].value_counts()

In [74]:
counts

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [77]:
df['brand'].nunique()
threshold=100

In [79]:
repl=counts[counts<=threshold].index

In [83]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4567,0,0,0,0,0,0,1,0,0,0,0,0,0
1023,0,0,1,0,0,0,0,0,0,0,0,0,0
3240,0,0,0,0,0,0,0,0,0,0,0,0,1
7976,0,0,0,0,0,0,1,0,0,0,0,0,0
2367,0,0,0,0,0,1,0,0,0,0,0,0,0